language: ruby
sudo: false
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
bundler_args: --without integration --deployment --jobs=3 --retry=3
cache: bundler
rvm:
  - 2.1
  - 2.2
script:
  - bundle exec rake travis
