name 'certbot'
maintainer 'Andy Thompson'
maintainer_email 'athompson@inviqa.com'
license 'apache2'
description 'Installs/Configures certbot'
long_description 'Installs/Configures certbot'
version '0.4.0'

issues_url 'https://github.com/avarteqgmbh/chef-certbot/issues'
source_url 'https://github.com/avarteqgmbh/chef-certbot'

depends 'cron'
depends 'nginx'
depends 'yum-epel'
depends 'test-helper'
