name 'fake'
maintainer 'Felicity Ratcliffe'
maintainer_email 'fratcliffe@inviqa.com'
license 'apache2'
description 'fake cookbook'
long_description 'fake cookbook'
version '0.1.0'

depends 'certbot'
depends 'apache2'
depends 'nginx'
